# SPDX-FileCopyrightText: (C) The Kokkos-FFT development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

AMD-MI300A:
  tags: [uo-gpu, odyssey, amd-mi300]
  image: rocm/dev-ubuntu-24.04:6.2.4-complete
  script:
    - apt-get update && apt-get install -y libgtest-dev cmake git
    - export HSA_XNACK=1
    - git clone https://github.com/kokkos/kokkos.git
    - cmake -S kokkos
            -B kokkos_build
            -D CMAKE_PREFIX_PATH=/opt/rocm-6.2.4
            -DCMAKE_INSTALL_PREFIX=kokkos_install
            -DCMAKE_CXX_COMPILER=hipcc
            -DKokkos_ENABLE_HIP=ON
    - cmake --build kokkos_build --parallel
    - cmake --install kokkos_build
    - export ENV_CMAKE_OPTIONS=""
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_BUILD_TYPE=Release"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CXX_COMPILER=hipcc"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_PREFIX_PATH=/opt/rocm-6.2.4"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D Kokkos_DIR=/builds/kokkos/kokkos-fft/kokkos_install/lib/cmake/Kokkos/"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CUDA_FLAGS='-Wall -Wextra'"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D KokkosFFT_ENABLE_EXAMPLES=ON"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D KokkosFFT_ENABLE_TESTS=ON"
    - export CTEST_BUILD_NAME="AMD-MI300A"
    - ctest -VV
        -D CDASH_MODEL=Nightly
        -D CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS}"
        -D OUTPUT_JUNIT_FILE=result_mi300a.xml
        -S .gitlab/CTestRun.cmake
        -D CTEST_SITE="gitlab.spack.io"
        -D CTEST_BUILD_NAME="${CTEST_BUILD_NAME}"
      | tee test_results.txt
  artifacts:
    when: always
    paths:
      - build/result_mi300a.xml
    reports:
      junit: build/result_mi300a.xml
