# SPDX-FileCopyrightText: (C) The Kokkos-FFT development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   fail_on_warning: false

python:
   install:
   - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - git
    - g++
    - make
