[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kokkos-fft-python"
version = "1.0"
readme = "../README.md"
requires-python = ">=3.8"
dependencies = [
  "pytest>=7.0"
  "pylint",
]

[tool.hatch.build.targets.wheel]
packages = ["python"]
