function(get_tpls_list tpls_list)
    if(Kokkos_ENABLE_CUDA)
        list(APPEND tpls_list CUFFT)
    elseif(Kokkos_ENABLE_HIP)
        if(KokkosFFT_ENABLE_ROCFFT)
            list(APPEND tpls_list ROCFFT)
        else()
            list(APPEND tpls_list HIPFFT)
        endif()
    elseif(Kokkos_ENABLE_SYCL)
        list(APPEND tpls_list ONEMKL)
    elseif(Kokkos_ENABLE_OPENMP)
        list(APPEND tpls_list FFTW_OPENMP)
    elseif(Kokkos_ENABLE_THREADS)
        list(APPEND tpls_list FFTW_THREADS)
    elseif(Kokkos_ENABLE_SERIAL)
        list(APPEND tpls_list FFTW)
    endif()

    if(KokkosFFT_ENABLE_HOST_AND_DEVICE)
        if(Kokkos_ENABLE_OPENMP)
            list(APPEND tpls_list FFTW_OPENMP)
        elseif(Kokkos_ENABLE_THREADS)
            list(APPEND tpls_list FFTW_THREADS)
        else()
            list(APPEND tpls_list FFTW)
        endif()
    endif()

    set(${tpls_list} ${${tpls_list}} PARENT_SCOPE)
endfunction()