# SPDX-FileCopyrightText: (C) The kokkos-fft development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

# This job checks the CMake formatting using the cmake-format lint action.
# If any formatting inconsistencies are found compared to the expected style, the job will fail 
# and the differences will be displayed in the job log.
# See https://github.com/puneetmatharu/cmake-format-lint-action for more details.

name: cmake-format check

on:
  workflow_call:

permissions: read-all

jobs:
  cmake-formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: cmake-format lint action
      uses: puneetmatharu/cmake-format-lint-action@2ac346e79e7ceac958bc637c1391285fb335ed7c # v1.0.5
      with:
        args: --config-files .cmake-format.py --in-place
        file-regex: '(.*\.cmake$|.*\.cmake\.in$|CMakeLists.txt$)'
    - name: check
      run: git diff --exit-code 
